# Generated by Django 3.0.1 on 2019-12-30 10:46

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True, blank=True, db_column='TimeCreated', default=django.utils.timezone.now, null=True)),
                ('guid', models.CharField(db_column='GUID', default=uuid.uuid1, editable=False, max_length=45)),
                ('username', models.CharField(db_column='UserName', db_index=True, max_length=25, unique=True, verbose_name='User Name')),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=45, null=True)),
                ('mobile', models.CharField(db_column='Mobile', max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered [01xxxxxxxxx] Num.', regex='^\\+?1?\\d{11,11}$')])),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Enter Valid E-mail.', regex='(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)')])),
                ('password', models.CharField(db_column='Password', max_length=100)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], db_column='Gender', null=True)),
                ('date_of_birth', models.DateField(blank=True, db_column='Birthday', null=True)),
                ('address', models.CharField(blank=True, db_column='Address1', max_length=100, null=True, verbose_name='Work Address')),
                ('time_modified', models.DateTimeField(auto_now=True, db_column='TimeModified', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='IsActive', default=True, null=True)),
                ('is_admin', models.BooleanField(blank=True, db_column='IsAdmin', default=False, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-time_created'],
            },
        ),
    ]
