INSERT INTO stock (Symbol, Name, Sector) VALUES ('MM', '3M Company', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OS', 'A.O. Smith Corp', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BT', 'Abbott Laboratories', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BBV', 'AbbVie Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CN', 'Accenture plc', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TVI', 'Activision Blizzard', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YI', 'Acuity Brands Inc', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DBE', 'Adobe Systems Inc', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AP', 'Advance Auto Parts', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MD', 'Advanced Micro Devices Inc', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ES', 'AES Corp', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ET', 'Aetna Inc', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MG', 'Affiliated Managers Group Inc', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FL', 'AFLAC Inc', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('', 'Agilent Technologies Inc', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PD', 'Air Products & Chemicals Inc', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('KAM', 'Akamai Technologies Inc', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LK', 'Alaska Air Group Inc', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LB', 'Albemarle Corp', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RE', 'Alexandria Real Estate Equities Inc', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LXN', 'Alexion Pharmaceuticals', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LGN', 'Align Technology', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LLE', 'Allegion', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('GN', 'Allergan, Plc', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DS', 'Alliance Data Systems', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NT', 'Alliant Energy Corp', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LL', 'Allstate Corp', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OOGL', 'Alphabet Inc Class A', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OOG', 'Alphabet Inc Class C', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('O', 'Altria Group Inc', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MZN', 'Amazon.com Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EE', 'Ameren Corp', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AL', 'American Airlines Group', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EP', 'American Electric Power', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XP', 'American Express Co', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IG', 'American International Group, Inc.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MT', 'American Tower Corp A', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WK', 'American Water Works Company Inc', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MP', 'Ameriprise Financial', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BC', 'AmerisourceBergen Corp', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ME', 'AMETEK Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MGN', 'Amgen Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PH', 'Amphenol Corp', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PC', 'Anadarko Petroleum Corp', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DI', 'Analog Devices, Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NDV', 'Andeavor', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NSS', 'ANSYS', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NTM', 'Anthem Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ON', 'Aon plc', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PA', 'Apache Corporation', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IV', 'Apartment Investment & Management', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('APL', 'Apple Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MAT', 'Applied Materials Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PTV', 'Aptiv Plc', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DM', 'Archer-Daniels-Midland Co', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RNC', 'Arconic Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('JG', 'Arthur J. Gallagher & Co.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IZ', 'Assurant Inc.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('', 'AT&T Inc.', 'Telecommunication Services');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DSK', 'Autodesk Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DP', 'Automatic Data Processing', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ZO', 'AutoZone Inc', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VB', 'AvalonBay Communities, Inc.', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VY', 'Avery Dennison Corp', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HGE', 'Baker Hughes, a GE Company', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LL', 'Ball Corp', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AC', 'Bank of America Corp', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AX', 'Baxter International Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BT', 'BB&T Corporation', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DX', 'Becton Dickinson', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RK.B', 'Berkshire Hathaway', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BY', 'Best Buy Co. Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IIB', 'Biogen Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LK', 'BlackRock', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RB', 'Block H&R', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('A', 'Boeing Company', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('KNG', 'Booking Holdings Inc', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WA', 'BorgWarner', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XP', 'Boston Properties', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SX', 'Boston Scientific', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HF', 'Brighthouse Financial Inc', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MY', 'Bristol-Myers Squibb', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VGO', 'Broadcom', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('F.B', 'Brown-Forman Corp.', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HRW', 'C. H. Robinson Worldwide', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('A', 'CA, Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OG', 'Cabot Oil & Gas', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DNS', 'Cadence Design Systems', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PB', 'Campbell Soup', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OF', 'Capital One Financial', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AH', 'Cardinal Health Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MX', 'Carmax Inc', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CL', 'Carnival Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AT', 'Caterpillar Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BOE', 'Cboe Global Markets', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BRE', 'CBRE Group', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BS', 'CBS Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ELG', 'Celgene Corp.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NC', 'Centene Corporation', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NP', 'CenterPoint Energy', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TL', 'CenturyLink Inc', 'Telecommunication Services');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ERN', 'Cerner', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('F', 'CF Industries Holdings Inc', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CHW', 'Charles Schwab Corporation', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HTR', 'Charter Communications', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VX', 'Chevron Corp.', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MG', 'Chipotle Mexican Grill', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('B', 'Chubb Limited', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HD', 'Church & Dwight', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('I', 'CIGNA Corp.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EC', 'Cimarex Energy', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('INF', 'Cincinnati Financial', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TAS', 'Cintas Corporation', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SCO', 'Cisco Systems', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('', 'Citigroup Inc.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FG', 'Citizens Financial Group', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TXS', 'Citrix Systems', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ME', 'CME Group Inc.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MS', 'CMS Energy', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('O', 'Coca-Cola Company (The)', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TSH', 'Cognizant Technology Solutions', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('L', 'Colgate-Palmolive', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MCSA', 'Comcast Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MA', 'Comerica Inc.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AG', 'Conagra Brands', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XO', 'Concho Resources', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OP', 'ConocoPhillips', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('D', 'Consolidated Edison', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TZ', 'Constellation Brands', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LW', 'Corning Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OST', 'Costco Wholesale Corp.', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OTY', 'Coty, Inc', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CI', 'Crown Castle International Corp.', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SRA', 'CSRA Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SX', 'CSX Corp.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MI', 'Cummins Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VS', 'CVS Health', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HI', 'D. R. Horton', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HR', 'Danaher Corp.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RI', 'Darden Restaurants', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VA', 'DaVita Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('E', 'Deere & Co.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AL', 'Delta Air Lines Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RAY', 'Dentsply Sirona', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VN', 'Devon Energy Corp.', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LR', 'Digital Realty Trust Inc', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FS', 'Discover Financial Services', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ISCA', 'Discovery Inc. Class A', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ISCK', 'Discovery Inc. Class C', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ISH', 'Dish Network', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('G', 'Dollar General', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LTR', 'Dollar Tree', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('', 'Dominion Energy', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OV', 'Dover Corp.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WDP', 'DowDuPont', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PS', 'Dr Pepper Snapple Group', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TE', 'DTE Energy Co.', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('UK', 'Duke Energy', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RE', 'Duke Realty Corp', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XC', 'DXC Technology', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TFC', 'E*Trade', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MN', 'Eastman Chemical', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TN', 'Eaton Corporation', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BAY', 'eBay Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CL', 'Ecolab Inc.', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IX', 'Edison Int''l', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('W', 'Edwards Lifesciences', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('A', 'Electronic Arts', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MR', 'Emerson Electric Company', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TR', 'Entergy Corp.', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VHC', 'Envision Healthcare', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OG', 'EOG Resources', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('QT', 'EQT Corporation', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FX', 'Equifax Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('QIX', 'Equinix', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('QR', 'Equity Residential', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SS', 'Essex Property Trust, Inc.', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('L', 'Estee Lauder Cos.', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('E', 'Everest Re Group Ltd.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('S', 'Eversource Energy', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XC', 'Exelon Corp.', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XPE', 'Expedia Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XPD', 'Expeditors International', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SRX', 'Express Scripts', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XR', 'Extra Space Storage', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OM', 'Exxon Mobil Corp.', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FIV', 'F5 Networks', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('B', 'Facebook, Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AST', 'Fastenal Co', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RT', 'Federal Realty Investment Trust', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DX', 'FedEx Corporation', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IS', 'Fidelity National Information Services', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ITB', 'Fifth Third Bancorp', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('E', 'FirstEnergy Corp', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ISV', 'Fiserv Inc', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LIR', 'FLIR Systems', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LS', 'Flowserve Corporation', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LR', 'Fluor Corp.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MC', 'FMC Corporation', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('L', 'Foot Locker Inc', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('', 'Ford Motor', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TV', 'Fortive Corp', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BHS', 'Fortune Brands Home & Security', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EN', 'Franklin Resources', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CX', 'Freeport-McMoRan Inc.', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PS', 'Gap Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RMN', 'Garmin Ltd.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('T', 'Gartner Inc', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('D', 'General Dynamics', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('E', 'General Electric', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('GP', 'General Growth Properties Inc.', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IS', 'General Mills', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('M', 'General Motors', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PC', 'Genuine Parts', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ILD', 'Gilead Sciences', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PN', 'Global Payments Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('S', 'Goldman Sachs Group', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('T', 'Goodyear Tire & Rubber', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WW', 'Grainger (W.W.) Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AL', 'Halliburton Co.', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BI', 'Hanesbrands Inc', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OG', 'Harley-Davidson', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RS', 'Harris Corporation', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IG', 'Hartford Financial Svc.Gp.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AS', 'Hasbro Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CA', 'HCA Holdings', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CP', 'HCP Inc.', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('P', 'Helmerich & Payne', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SIC', 'Henry Schein', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ES', 'Hess Corporation', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PE', 'Hewlett Packard Enterprise', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LT', 'Hilton Worldwide Holdings Inc', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OLX', 'Hologic', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('D', 'Home Depot', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ON', 'Honeywell Int''l Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RL', 'Hormel Foods Corp.', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ST', 'Host Hotels & Resorts', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PQ', 'HP Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('UM', 'Humana Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BAN', 'Huntington Bancshares', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('II', 'Huntington Ingalls Industries', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DXX', 'IDEXX Laboratories', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NFO', 'IHS Markit Ltd.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TW', 'Illinois Tool Works', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LMN', 'Illumina Inc', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NCY', 'Incyte', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('R', 'Ingersoll-Rand PLC', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NTC', 'Intel Corp.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CE', 'Intercontinental Exchange', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BM', 'International Business Machines', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('P', 'International Paper', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PG', 'Interpublic Group', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FF', 'Intl Flavors & Fragrances', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NTU', 'Intuit Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SRG', 'Intuitive Surgical Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VZ', 'Invesco Ltd.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PGP', 'IPG Photonics Corp.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('QV', 'IQVIA Holdings Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RM', 'Iron Mountain Incorporated', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BHT', 'J. B. Hunt Transport Services', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EC', 'Jacobs Engineering Group', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('JM', 'JM Smucker', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NJ', 'Johnson & Johnson', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CI', 'Johnson Controls International', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PM', 'JPMorgan Chase & Co.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NPR', 'Juniper Networks', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SU', 'Kansas City Southern', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('', 'Kellogg Co.', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EY', 'KeyCorp', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MB', 'Kimberly-Clark', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IM', 'Kimco Realty', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MI', 'Kinder Morgan', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LAC', 'KLA-Tencor Corp.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SS', 'Kohl''s Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HC', 'Kraft Heinz Co', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('R', 'Kroger Co.', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('B', 'L Brands Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LL', 'L-3 Communications Holdings', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('H', 'Laboratory Corp. of America Holding', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RCX', 'Lam Research', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EG', 'Leggett & Platt', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EN', 'Lennar Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('UK', 'Leucadia National Corp.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LY', 'Lilly (Eli) & Co.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NC', 'Lincoln National', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('KQ', 'LKQ Corporation', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MT', 'Lockheed Martin Corp.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('', 'Loews Corp.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OW', 'Lowe''s Cos.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YB', 'LyondellBasell', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TB', 'M&T Bank Corp.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AC', 'Macerich', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('', 'Macy''s Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RO', 'Marathon Oil Corp.', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PC', 'Marathon Petroleum', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AR', 'Marriott Int''l.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MC', 'Marsh & McLennan', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LM', 'Martin Marietta Materials', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AS', 'Masco Corp.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('A', 'Mastercard Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AT', 'Mattel Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('KC', 'McCormick & Co.', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CD', 'McDonald''s Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CK', 'McKesson Corp.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DT', 'Medtronic plc', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RK', 'Merck & Co.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ET', 'MetLife Inc.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TD', 'Mettler Toledo', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('GM', 'MGM Resorts International', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ORS', 'Michael Kors Holdings', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CHP', 'Microchip Technology', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('U', 'Micron Technology', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SFT', 'Microsoft Corp.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AA', 'Mid-America Apartments', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HK', 'Mohawk Industries', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AP', 'Molson Coors Brewing Company', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DLZ', 'Mondelez International', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ON', 'Monsanto Co.', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NST', 'Monster Beverage', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CO', 'Moody''s Corp', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('S', 'Morgan Stanley', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SI', 'Motorola Solutions Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YL', 'Mylan N.V.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DAQ', 'Nasdaq, Inc.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OV', 'National Oilwell Varco Inc.', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AVI', 'Navient', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('KTR', 'Nektar Therapeutics', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TAP', 'NetApp', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FLX', 'Netflix Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WL', 'Newell Brands', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FX', 'Newfield Exploration Co', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EM', 'Newmont Mining Corporation', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WSA', 'News Corp. Class A', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WS', 'News Corp. Class B', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EE', 'NextEra Energy', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LSN', 'Nielsen Holdings', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('KE', 'Nike', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('I', 'NiSource Inc.', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BL', 'Noble Energy Inc', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WN', 'Nordstrom', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SC', 'Norfolk Southern Corp.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TRS', 'Northern Trust Corp.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OC', 'Northrop Grumman Corp.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CLH', 'Norwegian Cruise Line', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RG', 'NRG Energy', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('UE', 'Nucor Corp.', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VDA', 'Nvidia Corporation', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RLY', 'O''Reilly Automotive', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XY', 'Occidental Petroleum', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MC', 'Omnicom Group', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('KE', 'ONEOK', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RCL', 'Oracle Corp.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CAR', 'PACCAR Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('KG', 'Packaging Corporation of America', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('H', 'Parker-Hannifin', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AYX', 'Paychex Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YPL', 'PayPal', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NR', 'Pentair Ltd.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BCT', 'People''s United Financial', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EP', 'PepsiCo Inc.', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('KI', 'PerkinElmer', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RGO', 'Perrigo', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FE', 'Pfizer Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CG', 'PG&E Corp.', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('M', 'Philip Morris International', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SX', 'Phillips 66', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NW', 'Pinnacle West Capital', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XD', 'Pioneer Natural Resources', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NC', 'PNC Financial Services', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('L', 'Polo Ralph Lauren Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PG', 'PPG Industries', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PL', 'PPL Corp.', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('X', 'Praxair Inc.', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FG', 'Principal Financial Group', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('G', 'Procter & Gamble', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('GR', 'Progressive Corp.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LD', 'Prologis', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RU', 'Prudential Financial', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EG', 'Public Serv. Enterprise Inc.', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SA', 'Public Storage', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HM', 'Pulte Homes Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('VH', 'PVH Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RVO', 'Qorvo', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('COM', 'QUALCOMM Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WR', 'Quanta Services Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('GX', 'Quest Diagnostics', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RC', 'Range Resources Corp.', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('JF', 'Raymond James Financial Inc.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TN', 'Raytheon Co.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('', 'Realty Income Corporation', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HT', 'Red Hat Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EG', 'Regency Centers Corporation', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EGN', 'Regeneron', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('F', 'Regions Financial Corp.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SG', 'Republic Services Inc', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MD', 'ResMed', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HI', 'Robert Half International', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OK', 'Rockwell Automation Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OL', 'Rockwell Collins', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OP', 'Roper Technologies', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OST', 'Ross Stores', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CL', 'Royal Caribbean Cruises Ltd', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PGI', 'S&P Global, Inc.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RM', 'Salesforce.com', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BAC', 'SBA Communications', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('CG', 'SCANA Corp', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LB', 'Schlumberger Ltd.', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TX', 'Seagate Technology', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EE', 'Sealed Air', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RE', 'Sempra Energy', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HW', 'Sherwin-Williams', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PG', 'Simon Property Group Inc', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WKS', 'Skyworks Solutions', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LG', 'SL Green Realty', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NA', 'Snap-On Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('O', 'Southern Co.', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('UV', 'Southwest Airlines', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WK', 'Stanley Black & Decker', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BUX', 'Starbucks Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TT', 'State Street Corp.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RCL', 'Stericycle Inc', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YK', 'Stryker Corp.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TI', 'SunTrust Banks', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IVB', 'SVB Financial', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YMC', 'Symantec Corp.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YF', 'Synchrony Financial', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NPS', 'Synopsys Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YY', 'Sysco Corp.', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ROW', 'T. Rowe Price Group', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TWO', 'Take-Two Interactive', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PR', 'Tapestry, Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('GT', 'Target Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EL', 'TE Connectivity Ltd.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TI', 'TechnipFMC', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XN', 'Texas Instruments', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('XT', 'Textron Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('K', 'The Bank of New York Mellon Corp.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LX', 'The Clorox Company', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OO', 'The Cooper Companies', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SY', 'The Hershey Company', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OS', 'The Mosaic Company', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RV', 'The Travelers Companies Inc.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IS', 'The Walt Disney Company', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MO', 'Thermo Fisher Scientific', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IF', 'Tiffany & Co.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('WX', 'Time Warner Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('JX', 'TJX Companies Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MK', 'Torchmark Corp.', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SS', 'Total System Services', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SCO', 'Tractor Supply Company', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DG', 'TransDigm Group', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RIP', 'TripAdvisor', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OXA', 'Twenty-First Century Fox Class A', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('OX', 'Twenty-First Century Fox Class B', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SN', 'Tyson Foods', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('SB', 'U.S. Bancorp', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DR', 'UDR Inc', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LTA', 'Ulta Beauty', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AA', 'Under Armour Class A', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('A', 'Under Armour Class C', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NP', 'Union Pacific', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AL', 'United Continental Holdings', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NH', 'United Health Group Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('PS', 'United Parcel Service', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RI', 'United Rentals, Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TX', 'United Technologies', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HS', 'Universal Health Services, Inc.', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NM', 'Unum Group', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FC', 'V.F. Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LO', 'Valero Energy', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AR', 'Varian Medical Systems', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TR', 'Ventas Inc', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RSN', 'Verisign Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RSK', 'Verisk Analytics', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('Z', 'Verizon Communications', 'Telecommunication Services');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RTX', 'Vertex Pharmaceuticals Inc', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('IAB', 'Viacom Inc.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('', 'Visa Inc.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('NO', 'Vornado Realty Trust', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MC', 'Vulcan Materials', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MT', 'Wal-Mart Stores', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BA', 'Walgreens Boots Alliance', 'Consumer Staples');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('M', 'Waste Management Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('AT', 'Waters Corporation', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EC', 'Wec Energy Group Inc', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('FC', 'Wells Fargo', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ELL', 'Welltower Inc.', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('DC', 'Western Digital', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('U', 'Western Union Co', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RK', 'WestRock Company', 'Materials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('Y', 'Weyerhaeuser Corp.', 'Real Estate');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('HR', 'Whirlpool Corp.', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('MB', 'Williams Cos.', 'Energy');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LTW', 'Willis Towers Watson', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YN', 'Wyndham Worldwide', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YNN', 'Wynn Resorts Ltd', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('EL', 'Xcel Energy Inc', 'Utilities');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('RX', 'Xerox Corp.', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('LNX', 'Xilinx Inc', 'Information Technology');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('L', 'XL Capital', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('YL', 'Xylem Inc.', 'Industrials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('UM', 'Yum! Brands Inc', 'Consumer Discretionary');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('BH', 'Zimmer Biomet Holdings', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('ION', 'Zions Bancorp', 'Financials');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('TS', 'Zoetis', 'Health Care');
INSERT INTO stock (Symbol, Name, Sector) VALUES ('Symbol', 'Name', 'Sector');

