# Generated by Django 3.0.1 on 2019-12-31 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True, blank=True, db_column='TimeCreated', default=django.utils.timezone.now, null=True)),
                ('time_deleted', models.DateTimeField(blank=True, db_column='TimeDeleted', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', default=False, null=True)),
                ('symbol', models.CharField(db_column='Symbol', db_index=True, max_length=10)),
                ('name', models.CharField(db_column='Name', db_index=True, max_length=100)),
                ('sector', models.CharField(blank=True, db_column='Sector', max_length=45, null=True)),
                ('info', models.TextField(blank=True, db_column='Info', null=True, verbose_name='Extra Info')),
                ('time_modified', models.DateTimeField(auto_now=True, db_column='TimeModified', null=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
                'ordering': ('sector', 'name'),
                'managed': False,
            },
        ),
    ]
