# Generated by Django 3.0.1 on 2019-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_column='Symbol', db_index=True, max_length=10)),
                ('name', models.CharField(db_column='Name', db_index=True, max_length=100)),
                ('sector', models.CharField(blank=True, db_column='Sector', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
                'ordering': ('sector', 'name'),
            },
        ),
    ]
