# Generated by Django 3.0.1 on 2019-12-30 19:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='creator',
            field=models.ForeignKey(blank=True, db_column='Creator', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='deleted',
            field=models.BooleanField(blank=True, db_column='Deleted', default=False, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='info',
            field=models.TextField(blank=True, db_column='Info', null=True, verbose_name='Extra Info'),
        ),
        migrations.AddField(
            model_name='stock',
            name='time_created',
            field=models.DateTimeField(auto_created=True, blank=True, db_column='TimeCreated', default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='time_deleted',
            field=models.DateTimeField(blank=True, db_column='TimeDeleted', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='time_modified',
            field=models.DateTimeField(auto_now=True, db_column='TimeModified', null=True),
        ),
    ]
