# Generated by Django 2.2 on 2020-03-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
