# Generated by Django 3.0.1 on 2019-12-30 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0002_auto_20191230_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='creator',
            field=models.ForeignKey(blank=True, db_column='Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
