# Generated by Django 2.2 on 2020-03-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('change', models.CharField(max_length=20)),
                ('change_p', models.CharField(max_length=20)),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
